apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: fashion-mnist-cloud
    labels:
        app: federated-learning
spec:
    selector:
        matchLabels:
            app: federated-learning
    serviceName: "federated-learning-svc"  
    replicas: 1 
    template:
        metadata:
            labels:
                app: federated-learning
        spec:
            terminationGracePeriodSeconds: 10
            nodeName: cloud
            containers:
            - name: federated-learning
              image: flower/fashion-mnist-aggregator:v1.0.9
#              resources:
#                requests:
#                    memory: "2Gi"
#                    cpu: "2"
#                limits:
#                    memory: "4Gi" 
#                    cpu: "4"
              args: ["--rounds= 50", "--sample_fraction=1", "--min_sample_size=11", "--min_num_clients=11", "--round_timeout=6000", "--enable_latency_capture=0","--epochs=2", "--batch_size=64", "--server_address=0.0.0.0:8888"] # round to change 
              ports:
                   -   containerPort: 8888
            hostNetwork: true #false: provide IP for cloud pod, true: use its cloud IP
            dnsPolicy: Default
    #restartPolicy: Never
# ---
###NODE CLOUD####
# apiVersion: v1
# kind: Pod
# metadata: 
    # name: fashion-mnist
    # labels:
        # app: federated-learning
# spec:  
    # nodeName: cloud
    # containers: 
      # - image: kubeedge/fashion-mnist-aggregator:v1.0.0
        # name: federated-learning
        # args: ["--rounds=5", "--sample_fraction=0.5", "--min_sample_size=2", "--min_num_clients=2", "--server_address=0.0.0.0:8888"]
        # ports:
        # -   containerPort: 8888
    # hostNetwork: true
    # dnsPolicy: Default
    # restartPolicy: Never

# ---
# ###SERVICE####
# apiVersion: v1
# kind: Service
# metadata:
    # name: federated-learning-svc
# spec:
    # selector:
        # app: federated-learning
    # ports:
         # -  port: 12345
            # protocol: TCP
            # targetPort: 8888
# ---
# ###HPA AutoScaler###
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
    # name: fashion-mnist
    # namespace: default
# spec:
    # scaleTargetRef:
        # apiVersion: apps/v1
        # kind: Deployment
        # name: fashion-mnist
    # minReplicas: 1
    # maxReplicas: 10
    # targetCPUUtilizationPercentage: 85
---
apiVersion: v1
kind: Service
metadata:
  name: federated-learning-svc
spec:
  type: NodePort
  selector:
    app: federated-learning
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 12345 #~8888
      targetPort: 8888
      # Optional field
# By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30009


